name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  lint:
    uses: dmptrluke/workflows/.github/workflows/django-lint.yml@main

  release:
    needs: lint
    uses: dmptrluke/workflows/.github/workflows/django-release.yml@main
